---
- name: Include variables
  ansible.builtin.include_tasks: variables.yml

- name: Install Haproxy (Debian)
  become: true
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
    cache_valid_time: 1800
  when: ansible_distribution == "Debian"

- name: Install Haproxy (Arch)
  become: true
  ansible.builtin.package:
    name: haproxy
    state: present
  when: ansible_distribution == "Archlinux"

- name: Create Haproxy systemd drop-in directory
  become: true
  ansible.builtin.file:
    dest: /etc/systemd/system/haproxy.service.d
    state: directory
    mode: "0644"

- name: Create haproxy conf.d directory
  become: true
  ansible.builtin.file:
    dest: /etc/haproxy/conf.d
    state: directory
    mode: "0644"

- name: Copy Haproxy config script
  become: true
  ansible.builtin.copy:
    src: gen-conf.sh
    dest: /etc/haproxy/gen-conf.sh
    owner: root
    group: root
    mode: "0744"

- name: Configure haproxy to use conf.d-style configs
  become: true
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/haproxy.service.d/ansible.conf
    owner: root
    group: root
    mode: "0644"
  register: dropindir

- name: Setup chroot
  become: true
  ansible.builtin.file:
    dest: /var/lib/haproxy
    state: directory
    mode: "0644"
  when: ansible_distribution == "Archlinux" and haproxy_chroot

- name: Setup error page directory
  become: true
  ansible.builtin.file:
    dest: /etc/haproxy/errors
    state: directory
    mode: "0644"

- name: Copy error pages
  become: true
  ansible.builtin.copy:
    src: "{{ item }}.http"
    dest: "/etc/haproxy/errors/{{ item }}.http"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - 400
    - 403
    - 408
    - 500
    - 502
    - 503
    - 504

- name: Copy haproxy base config
  become: true
  ansible.builtin.template:
    src: 01-defaults.conf.j2
    dest: /etc/haproxy/conf.d/01-defaults.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Haproxy
