---
  - name: Install haproxy
    become: True
    apt:
      name: haproxy
      state: present
      update_cache: yes
      cache_valid_time: 1800
      default_release: "{{ haproxy_debian_release }}"

  - name: Create haproxy systemd drop-in directory
    become: True
    file: dest=/etc/systemd/system/haproxy.service.d state=directory

  - name: Create haproxy conf.d directory
    become: True
    file: dest=/etc/haproxy/conf.d state=directory

  - name: Copy haproxy config script
    become: True
    copy: src=gen-conf.sh dest=/etc/haproxy/gen-conf.sh owner=root group=root mode=0744

  - name: Configure haproxy to use conf.d-style configs
    become: True
    copy: src=haproxy-systemd.conf dest=/etc/systemd/system/haproxy.service.d/ansible.conf owner=root group=root mode=0644
    register: dropindir

  - name: reload systemd
    become: True
    command: systemctl daemon-reload
    when: dropindir.changed

  - name: Copy haproxy base config
    become: True
    template:
      src: 01-defaults.conf.j2
      dest: /etc/haproxy/conf.d/01-defaults.conf
      owner: root
      group: root
      mode: 0644
    notify: restart HAproxy
