---

  - include_tasks: variables.yml

  - name: Install haproxy
    become: True
    apt:
      name: haproxy
      state: present
      default_release: "{{ haproxy_debian_release }}"
    when: ansible_distribution == "Debian"

  - name: Install haproxy
    become: True
    package:
      name: haproxy
      state: present
    when: ansible_distribution == "Archlinux"

  - name: Create haproxy directories
    become: True
    file:
      path: /etc/systemd/system/haproxy.service.d
      state: directory
    loop:
      - "/etc/systemd/system/haproxy.service.d"
      - "/etc/haproxy/conf.d"
      - "/etc/haproxy/errors"

  - name: Copy haproxy config script
    become: True
    copy: src=gen-conf.sh dest=/etc/haproxy/gen-conf.sh owner=root group=root mode=0744

  - name: Configure haproxy to use conf.d-style configs
    become: True
    template: src=systemd.service.j2 dest=/etc/systemd/system/haproxy.service.d/ansible.conf owner=root group=root mode=0644
    register: dropindir

  - name: Setup chroot
    become: True
    file: dest=/var/lib/haproxy state=directory
    when: ansible_distribution == "Archlinux" and haproxy_chroot

  - name: Copy error pages
    become: True
    copy:
      src: "error_pages/"
      dest: "/etc/haproxy/errors/"
      owner: root
      group: root
      mode: 0644

  - name: reload systemd
    become: True
    systemd:
      daemon_reload: True
    when: dropindir.changed

  - name: Copy haproxy base config
    become: True
    template:
      src: 01-defaults.conf.j2
      dest: /etc/haproxy/conf.d/01-defaults.conf
      owner: root
      group: root
      mode: 0644
    notify: restart HAproxy
