---
  - name: Install haproxy
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
    with_items:
      - haproxy

  - name: Create haproxy systemd drop-in directory
    file: dest=/etc/systemd/system/haproxy.service.d state=directory

  - name: Create haproxy conf.d directory
    file: dest=/etc/haproxy/conf.d state=directory

  - name: Copy haproxy config script
    copy: src=gen-conf.sh dest=/etc/haproxy/gen-conf.sh owner=root group=root mode=0744

  - name: Configure haproxy to use conf.d-style configs
    copy: src=haproxy-systemd.conf dest=/etc/systemd/system/haproxy.service.d/ansible.conf owner=root group=root mode=0644
    register: dropindir

  - name: reload systemd
    command: systemctl daemon-reload
    when: dropindir.changed

  - name: Copy haproxy base config
    copy: src=01-defaults.conf dest=/etc/haproxy/conf.d/01-defaults.conf owner=root group=root mode=0644
    notify: restart HAproxy
