---
- name: Include variables
  ansible.builtin.include_tasks: variables.yml

- name: Install Haproxy (Debian)
  become: true
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true
    cache_valid_time: 1800
    default_release: "{{ haproxy_debian_release }}"
  when: ansible_facts.distribution == "Debian"

- name: Install Haproxy (Arch)
  become: true
  ansible.builtin.package:
    name: haproxy
    state: present
  when: ansible_facts.distribution == "Archlinux"

- name: Create Haproxy directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0644"
  loop:
    - "/etc/systemd/system/haproxy.service.d"
    - "/etc/haproxy/conf.d"
    - "/etc/haproxy/errors"

- name: Copy Haproxy config script
  become: true
  ansible.builtin.copy:
    src: gen-conf.sh
    dest: /etc/haproxy/gen-conf.sh
    owner: root
    group: root
    mode: "0744"

- name: Configure haproxy to use conf.d-style configs
  become: true
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/haproxy.service.d/ansible.conf
    owner: root
    group: root
    mode: "0644"
  notify: HAProxy Systemd Daemon Reload

- name: Setup chroot
  become: true
  ansible.builtin.file:
    dest: /var/lib/haproxy
    state: directory
    mode: "0644"
  when: ansible_facts.distribution == "Archlinux" and haproxy_chroot


- name: Copy error pages
  become: true
  ansible.builtin.copy:
    src: "error_pages/"
    dest: "/etc/haproxy/errors/"
    owner: root
    group: root
    mode: "0644"

- name: Copy DH Params
  become: true
  ansible.builtin.copy:
    src: dh-params.txt
    dest: /etc/haproxy/dh-params.txt
    owner: root
    group: root
    mode: "0644"
  when: haproxy_use_provided_dhparams

- name: Copy haproxy base config
  become: true
  ansible.builtin.template:
    src: 01-defaults.conf.j2
    dest: /etc/haproxy/conf.d/01-defaults.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Haproxy
