---
- name: Include OS-specific variables (Debian).
  include_vars: "Debian.yml"
  when: ansible_facts.os_family == "Debian"

- name: Include OS-specific variables (Archlinux).
  include_vars: "Archlinux.yml"
  when: ansible_facts.os_family == "Archlinux"
